name: goz_player
description: Goz Player - A beautiful music player app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # A powerful package for internationalization and localization.
  intl: ^0.19.0
  # Provides a comprehensive set of Cupertino (iOS-style) icons.
  cupertino_icons: ^1.0.2
  # Efficiently downloads, caches, and displays images from the web.
  cached_network_image: ^3.3.1
  # A simple service locator for dependency injection in Flutter apps.
  get_it: ^7.6.7
  # A powerful HTTP client for handling REST API requests.
  dio: ^5.4.1
  # A simple package for making HTTP requests.
  http: ^1.6.0
  # State management library that helps manage states in a predictable way.
  flutter_bloc: ^8.1.3
  # Functional programming package for handling optional and either types.
  dartz: ^0.10.1
  # Simplifies equality comparisons and state management in Flutter.
  equatable: ^2.0.5
  # A plugin for SQLite database management, allowing local storage of data.
  sqflite: ^2.3.2
  # Stores key-value pairs in persistent storage.
  shared_preferences: ^2.3.2
  # Provides the correct paths to store files in different platforms.
  path_provider: ^2.1.4
  # A utility package for manipulating file paths.
  path: ^1.9.0
  # A comprehensive audio playback and service management library.
  audio_service: ^0.18.15
  # A feature-rich package for audio playback in Flutter apps.
  just_audio: ^0.10.5
  # A simple package to check internet connectivity status.
  internet_connection_checker: ^1.0.0+1
  # Provides access to network connectivity information.
  connectivity_plus: ^5.0.2
  # A widget for displaying an audio or video progress bar.
  audio_video_progress_bar: ^2.0.3
  # Adds a customizable tap animation effect for widgets.
  zoom_tap_animation: ^1.1.0
  # A package for displaying toast notifications in Flutter apps.
  fluttertoast: ^9.0.0
  # A widget that adds fading effects at the edges of a scroll view.
  fading_edge_scrollview: ^4.1.1
  # A package for launching URLs in the browser, SMS, or email.
  url_launcher: ^6.1.5
  # A package for caching network images.
  flutter_svg: ^2.2.2
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  isar_community_generator: ^3.3.0

  #Changing app & package name
  rename: ^3.0.1
  # rename setAppName --targets ios,android --value "YourAppName"

  #Changing app icon
  flutter_launcher_icons: ^0.13.1

  #Creating native splash
  flutter_native_splash: ^2.4.1

# dart run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/icon.png
  image_path_ios: assets/icons/iconIOS.png
  min_sdk_android: 21 # android min sdk min:16, default 21

#  dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/icons/icon.png
  color: "#3A40D3"
  android: true
  ios: true
  android_12:
    color: "#3A40D3"
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/icons/iconAPI31.png

    #App icon background color.
    icon_background_color: "#3A40D3"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/covers/
    - assets/catalog.json